### ISSUE TITLE
The security token included in the request is expired

### ISSUE THREAD

**Issue by nford** [remind101/assume-role#20]
I have a long running stack deployment (CloudFront), using this with Serverless, MFA, and just had the whole thing quit with "The security token included in the request is expired".
 
What to do?

**Comment by ejholmes** [comment]
AWS STS credentials have a maximum lifetime of 1 hour, and there's not way around that without using boto3 profiles natively (so requests can retry if the credentials expire). `assume-role` is mostly a workaround for things that don't support boto3 profiles.

I'm not familiar with https://github.com/serverless/serverless, but you may be able to just use `export AWS_PROFILE=<xx>` instead of using `assume-role`.

**Comment by nford** [comment]
In my case it seems to be expiring after 30 minutes. I decided to use assume-role because of MFA.

**Comment by phobologic** [comment]
Hey @nford  - you can actually use MFA with the aws cli/profiles/cross account stuff these days as well:

http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html#cli-roles-xaccount
